# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: coding4kicks
subtitle: Have opinion. Will travel.
description: Coding, tech, politics, defense, whatever...
author: Scott Young
email: poof@coding4kicks.com
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://coding4kicks.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Disqus
disqus_shortname: coding4kicks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: hueman

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type:

# Logo Url
# Please enter the absolute path to your logo file
# or remove the following line with replacing logo-header.png with your own logo
logo: /css/images/logo-header.png

# Header
menu:
  Home: /
  # Delete this row if you don't want categories in your header nav bar
  Categories:
  About: /about/index.html

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Scroll Loading
scrollLoading: false

# Sidebar
social_links:
  twitter: https://twitter.com/coding4kicks
  github: https://github.com/coding4kicks

widgets:
- recent_posts
- category
- archive
- tag
- tagcloud
- links

# Links
links:
  Sendify - "The web in your email": http://sendify.io/
  Crowdabout (unmaintained): http://www.crowdabout.co/#/
  Parallel Spider (unmaintained): http://www.parallelspider.com/#/
  Old Website: http://coding4kicks-old.s3-website-us-east-1.amazonaws.com/#/
  Hexo: http://hexo.io

# Don't Use Google APIs if you are in google-blocked areas
use_google_apis: false

# Miscellaneous
google_analytics: UA-44221809-1
favicon: /favicon.png
fb_admins:
fb_app_id: 957250834319312
